"""added password

Revision ID: 267ecbef0663
Revises: 486c3f21fc2b
Create Date: 2024-09-08 20:13:33.600133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267ecbef0663'
down_revision = '486c3f21fc2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
